import { useCallback, useState } from "react";
import { createContentGeneration } from "../../application/create-content-generation.usecase";
import { editImage } from "../../application/edit-image.usecase";
import { getContentGenerationById } from "../../application/get-content-generation-by-id.usecase";
import { getContentGenerations } from "../../application/get-content-generations.usecase";
import { updateContentStatus } from "../../application/update-content-status.usecase";
import { ContentGenerationStatus } from "../../domain/enums/content-generation-status.enum";
import type {
	IContentGeneration,
	IContentGenerationResponse,
} from "../../domain/interfaces/content-generation.interface";
import type {
	ContentGenerationFilters,
	CreateContentGenerationRequest,
	EditImageResult,
} from "../../domain/ports/content-generation.port";
import { ContentGenerationAdapter } from "../../infrastructure/adapters/content-generation.adapter";

const contentGenerationRepository = new ContentGenerationAdapter();

export interface UseContentGenerationReturn {
	contentGenerations: IContentGeneration[];
	totalCount: number;
	currentPage: number;
	totalPages: number;
	loading: boolean;
	error: string | null;
	fetchContentGenerations: (
		filters?: ContentGenerationFilters
	) => Promise<void>;
	fetchContentGenerationById: (
		id: string
	) => Promise<IContentGeneration | null>;
	publishContent: (id: string) => Promise<IContentGeneration>;
	deleteContent: (id: string) => Promise<IContentGeneration>;
	markAsCompleted: (id: string) => Promise<IContentGeneration>;
	generateContent: (
		request: CreateContentGenerationRequest
	) => Promise<IContentGeneration>;
	editImage: (
		id: string,
		prompt: string,
		imageUrls?: string[]
	) => Promise<EditImageResult>;
}

/**
 * Hook for managing content generations
 * Provides methods to fetch, update status, and manage content generated by Linda
 */
export function useContentGeneration(): UseContentGenerationReturn {
	const [contentGenerations, setContentGenerations] = useState<
		IContentGeneration[]
	>([]);
	const [totalCount, setTotalCount] = useState(0);
	const [currentPage, setCurrentPage] = useState(1);
	const [totalPages, setTotalPages] = useState(1);
	const [loading, setLoading] = useState(false);
	const [error, setError] = useState<string | null>(null);

	/**
	 * Fetch content generations with optional filters
	 */
	const fetchContentGenerations = useCallback(
		async (filters?: ContentGenerationFilters) => {
			setLoading(true);
			setError(null);

			try {
				const response: IContentGenerationResponse =
					await getContentGenerations(contentGenerationRepository, filters);

				setContentGenerations(response.data);
				setTotalCount(response.total);
				setCurrentPage(response.page);
				setTotalPages(response.totalPages);
			} catch (err) {
				const errorMessage =
					err instanceof Error
						? err.message
						: "Failed to fetch content generations";
				setError(errorMessage);
				console.error("Error fetching content generations:", err);
			} finally {
				setLoading(false);
			}
		},
		[]
	);

	/**
	 * Fetch a specific content generation by ID
	 */
	const fetchContentGenerationById = useCallback(
		async (id: string): Promise<IContentGeneration | null> => {
			setLoading(true);
			setError(null);

			try {
				const content = await getContentGenerationById(
					contentGenerationRepository,
					id
				);
				return content;
			} catch (err) {
				const errorMessage =
					err instanceof Error
						? err.message
						: "Failed to fetch content generation";
				setError(errorMessage);
				console.error("Error fetching content generation:", err);
				return null;
			} finally {
				setLoading(false);
			}
		},
		[]
	);

	/**
	 * Publish content (update status to PUBLISHED)
	 */
	const publishContent = useCallback(
		async (id: string): Promise<IContentGeneration> => {
			setLoading(true);
			setError(null);

			try {
				const updatedContent = await updateContentStatus(
					contentGenerationRepository,
					id,
					ContentGenerationStatus.PUBLISHED
				);

				// Update local state
				setContentGenerations((prev) =>
					prev.map((content) => (content.id === id ? updatedContent : content))
				);

				return updatedContent;
			} catch (err) {
				const errorMessage =
					err instanceof Error ? err.message : "Failed to publish content";
				setError(errorMessage);
				console.error("Error publishing content:", err);
				throw err;
			} finally {
				setLoading(false);
			}
		},
		[]
	);

	/**
	 * Delete content (update status to DELETED)
	 */
	const deleteContent = useCallback(
		async (id: string): Promise<IContentGeneration> => {
			setLoading(true);
			setError(null);

			try {
				const updatedContent = await updateContentStatus(
					contentGenerationRepository,
					id,
					ContentGenerationStatus.DELETED
				);

				// Remove from local state
				setContentGenerations((prev) =>
					prev.filter((content) => content.id !== id)
				);

				return updatedContent;
			} catch (err) {
				const errorMessage =
					err instanceof Error ? err.message : "Failed to delete content";
				setError(errorMessage);
				console.error("Error deleting content:", err);
				throw err;
			} finally {
				setLoading(false);
			}
		},
		[]
	);

	/**
	 * Mark content as completed (update status to COMPLETED)
	 */
	const markAsCompleted = useCallback(
		async (id: string): Promise<IContentGeneration> => {
			setLoading(true);
			setError(null);

			try {
				const updatedContent = await updateContentStatus(
					contentGenerationRepository,
					id,
					ContentGenerationStatus.COMPLETED
				);

				// Update local state
				setContentGenerations((prev) =>
					prev.map((content) => (content.id === id ? updatedContent : content))
				);

				return updatedContent;
			} catch (err) {
				const errorMessage =
					err instanceof Error
						? err.message
						: "Failed to mark content as completed";
				setError(errorMessage);
				console.error("Error marking content as completed:", err);
				throw err;
			} finally {
				setLoading(false);
			}
		},
		[]
	);

	/**
	 * Generate new content with Linda AI
	 */
	const generateContent = useCallback(
		async (
			request: CreateContentGenerationRequest
		): Promise<IContentGeneration> => {
			setLoading(true);
			setError(null);

			try {
				const newContent = await createContentGeneration(
					contentGenerationRepository,
					request
				);

				// Add to local state
				setContentGenerations((prev) => [newContent, ...prev]);
				setTotalCount((prev) => prev + 1);

				return newContent;
			} catch (err) {
				const errorMessage =
					err instanceof Error ? err.message : "Failed to generate content";
				setError(errorMessage);
				console.error("Error generating content:", err);
				throw err;
			} finally {
				setLoading(false);
			}
		},
		[]
	);

	/**
	 * Edit image in content generation with Linda AI
	 */
	const editImageContent = useCallback(
		async (
			id: string,
			prompt: string,
			imageUrls?: string[]
		): Promise<EditImageResult> => {
			setLoading(true);
			setError(null);

			try {
				const result = await editImage(
					contentGenerationRepository,
					id,
					prompt,
					imageUrls
				);

				// Update local state with updated content
				setContentGenerations((prev) =>
					prev.map((content) =>
						content.id === id ? result.content : content
					)
				);

				return result;
			} catch (err) {
				const errorMessage =
					err instanceof Error ? err.message : "Failed to edit image";
				setError(errorMessage);
				console.error("Error editing image:", err);
				throw err;
			} finally {
				setLoading(false);
			}
		},
		[]
	);

	return {
		contentGenerations,
		totalCount,
		currentPage,
		totalPages,
		loading,
		error,
		fetchContentGenerations,
		fetchContentGenerationById,
		publishContent,
		deleteContent,
		markAsCompleted,
		generateContent,
		editImage: editImageContent,
	};
}
