import type { IField } from "../interfaces/field.interface";
import { EnumFieldType } from "../types/data-type.type";

export const FIELDS: IField[] = [
	{
		key: "contact",
		label: "clients_column_contact",
		isVisible: true,
		canHide: false,
		icon: "solar:user-linear",
		dataType: EnumFieldType.Text,
		sortable: true,
	},
	{
		key: "ai_tags",
		label: "clients_column_ai_tags",
		isVisible: true,
		canHide: false,
		icon: "solar:tag-linear",
		dataType: EnumFieldType.Text,
	},
	{
		key: "status",
		label: "clients_column_status",
		isVisible: true,
		canHide: false,
		icon: "solar:shield-check-linear",
		dataType: EnumFieldType.Text,
	},
	{
		key: "potency",
		label: "clients_column_potency",
		isVisible: true,
		canHide: false,
		icon: "solar:bolt-outline",
		dataType: EnumFieldType.Text,
	},
	{
		key: "quick_actions",
		label: "clients_column_quick_actions",
		isVisible: true,
		canHide: false,
		icon: "hugeicons:touch-interaction-04",
		dataType: EnumFieldType.Text,
	},
	{
		key: "email",
		label: "clients_column_email",
		isVisible: true,
		canHide: true,
		icon: "material-symbols:mail-outline-rounded",
		dataType: EnumFieldType.Text,
		sortable: true,
	},
	{
		key: "phone",
		label: "clients_column_phone",
		isVisible: true,
		canHide: true,
		icon: "solar:phone-linear",
		dataType: EnumFieldType.Text,
	},
	{
		key: "created_channel",
		label: "clients_column_created_channel",
		isVisible: true,
		canHide: true,
		icon: "solar:channel-linear",
		dataType: EnumFieldType.Text,
	},
	{
		key: "gender",
		label: "clients_column_gender",
		isVisible: true,
		canHide: true,
		icon: "solar:gender-linear",
		dataType: EnumFieldType.Text,
	},
	{
		key: "birthdate",
		label: "clients_column_birthdate",
		isVisible: true,
		canHide: true,
		icon: "hugeicons:birthday-cake",
		dataType: EnumFieldType.Date,
	},
	{
		key: "last_communication",
		label: "clients_column_last_communication",
		isVisible: true,
		canHide: true,
		icon: "solar:history-linear",
		dataType: EnumFieldType.Date,
	},
];
