/**
 * DTOs for Smart Tags API responses
 */

export interface SmartTagBasicInfoDto {
	title: string;
	description: string;
	color: string;
}

export interface SmartTagTemporalityDto {
	defaultDuration: number | null;
	allowCustomDuration: boolean;
	suggestedDurations: number[];
	autoRemove: boolean;
	isTemporary: boolean;
}

export interface SmartTagAiConfigDto {
	canBeAutoGenerated: boolean;
	requiresApproval: boolean;
	minimumConfidence: number;
}

export interface SmartTagResponseDto {
	type: string; // ACTION, OBJECTIVE, INTEREST, etc.
	basicInfo: SmartTagBasicInfoDto;
	keywords: string[];
	temporality: SmartTagTemporalityDto;
	aiConfig: SmartTagAiConfigDto;
	applicableEntities: string[]; // CLIENT, COMMUNICATION
	status: string; // ACTIVE, INACTIVE, DRAFT (in filters: DEPRECATED)
	id: string;
	agencyId: string;
	companyId: string;
	createdBy: string;
	sourceType: string; // AI_AUTO, AI_MANUAL, MANUAL
	usageCount: number;
	createdAt: string;
	updatedAt: string;
}

export interface GetSmartTagsResponseDto {
	items: SmartTagResponseDto[];
	total: number;
}

export interface GetSmartTagsApiResponse {
	success: boolean;
	message: string;
	data: GetSmartTagsResponseDto;
	timestamp: string;
}

/**
 * DTOs for Create Smart Tag
 */
export interface CreateSmartTagRequestDto {
	basicInfo: SmartTagBasicInfoDto;
	keywords: string[];
	type: string; // INTEREST, ACTION, OBJECTIVE, etc.
	status: string; // ACTIVE, INACTIVE, DRAFT
	applicableEntities: string[]; // CLIENT, COMMUNICATION
}

export interface CreateSmartTagApiResponse {
	success: boolean;
	message: string;
	data: SmartTagResponseDto;
	timestamp: string;
}

/**
 * DTOs for Update Smart Tag
 * All fields are optional to allow partial updates
 */
export interface UpdateSmartTagRequestDto {
	basicInfo?: SmartTagBasicInfoDto;
	keywords?: string[];
	type?: string; // INTEREST, ACTION, OBJECTIVE, etc.
	status?: string; // ACTIVE, INACTIVE, DRAFT
	applicableEntities?: string[]; // CLIENT, COMMUNICATION
	temporality?: SmartTagTemporalityDto;
}

export interface UpdateSmartTagApiResponse {
	success: boolean;
	message: string;
	data: SmartTagResponseDto;
	timestamp: string;
}
